import fs from "fs";
import path from "path";
import yaml from "js-yaml";

const dataDir = path.join(process.cwd(), "data", "systems");
const outputFile = path.join(process.cwd(), "lib", "generated-data.ts");

interface SystemInfo {
  id: string;
  name: string;
}

interface LineInfo {
  id: string;
  name: string;
}

interface StationData {
  station_name?: string;
  status?: string;
  platforms: {
    [line: string]: {
      [direction: string]: {
        door_side?: string;
        exits?: {
          [exitName: string]: string | number;
        };
      };
    };
  };
}

function generateDataModule() {
  // Read systems.yaml
  const systemsYamlPath = path.join(process.cwd(), "data", "systems", "systems.yaml");
  let systems: SystemInfo[] = [];
  
  if (fs.existsSync(systemsYamlPath)) {
    const systemsData = yaml.load(fs.readFileSync(systemsYamlPath, "utf8")) as SystemInfo[];
    if (Array.isArray(systemsData)) {
      systems = systemsData;
    }
  }
  
  // Fallback: read from directories
  if (systems.length === 0) {
    const systemsDirs = fs.readdirSync(dataDir, { withFileTypes: true });
    systems = systemsDirs
      .filter((dirent) => dirent.isDirectory() && dirent.name !== "systems")
      .map((dirent) => ({
        id: dirent.name,
        name: dirent.name.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase()),
      }));
  }

  const systemsData: Record<string, any> = {};
  const linesData: Record<string, LineInfo[]> = {};
  const stationsData: Record<string, Record<string, StationData>> = {};

  // Process each system
  for (const system of systems) {
    const systemPath = path.join(dataDir, system.id);
    
    // Read lines
    const linesPath = path.join(systemPath, "lines.yaml");
    if (fs.existsSync(linesPath)) {
      const linesFile = yaml.load(fs.readFileSync(linesPath, "utf8")) as LineInfo[] | string[];
      if (Array.isArray(linesFile)) {
        if (linesFile.length > 0 && typeof linesFile[0] === "object" && "id" in linesFile[0]) {
          linesData[system.id] = linesFile as LineInfo[];
        } else {
          linesData[system.id] = (linesFile as string[]).map((line) => ({
            id: String(line),
            name: String(line),
          }));
        }
      }
    }

    // Read stations
    const stationsPath = path.join(systemPath, "stations");
    if (fs.existsSync(stationsPath)) {
      stationsData[system.id] = {};
      const stationFiles = fs.readdirSync(stationsPath);
      
      for (const file of stationFiles) {
        if (file.endsWith(".yaml")) {
          const stationId = file.replace(".yaml", "");
          const stationPath = path.join(stationsPath, file);
          try {
            const stationData = yaml.load(fs.readFileSync(stationPath, "utf8")) as StationData;
            
            // Clean up null values in platforms (empty YAML entries become null)
            if (stationData.platforms) {
              Object.keys(stationData.platforms).forEach((lineId) => {
                const linePlatforms = stationData.platforms[lineId];
                Object.keys(linePlatforms).forEach((direction) => {
                  if (linePlatforms[direction] === null || linePlatforms[direction] === undefined) {
                    linePlatforms[direction] = {};
                  }
                });
              });
            }
            
            stationsData[system.id][stationId] = stationData;
          } catch (error) {
            console.error(`Error loading station ${stationId} in ${system.id}:`, error);
          }
        }
      }
    }
  }

  // Generate TypeScript file
  const output = `// This file is auto-generated by scripts/generate-data.ts
// Do not edit manually - run 'npm run generate-data' to regenerate

export interface SystemInfo {
  id: string;
  name: string;
}

export interface LineInfo {
  id: string;
  name: string;
}

export interface StationData {
  station_name?: string;
  status?: string;
  platforms: {
    [line: string]: {
      [direction: string]: {
        door_side?: string;
        exits?: {
          [exitName: string]: string | number;
        };
      };
    };
  };
}

export const systems: SystemInfo[] = ${JSON.stringify(systems, null, 2)};

export const lines: Record<string, LineInfo[]> = ${JSON.stringify(linesData, null, 2)};

export const stations: Record<string, Record<string, StationData>> = ${JSON.stringify(stationsData, null, 2)};
`;

  fs.writeFileSync(outputFile, output, "utf8");
  console.log(`✓ Generated data module at ${outputFile}`);
  console.log(`  - ${systems.length} systems`);
  console.log(`  - ${Object.keys(linesData).length} systems with lines`);
  console.log(`  - ${Object.values(stationsData).reduce((sum, sys) => sum + Object.keys(sys).length, 0)} stations`);
}

generateDataModule();

